baseURL = "https://jcvincentliu.netlify.app/"
title = "Vincent Liu"
theme = "gokarna"
googleAnalytics = "G-HCZW5878PF"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "native"

[params]
  footer = "Vincent Liu"
  showPostsOnHomePage = "recent"
  description = "Impact-driven in criminal justice and education with data science, rigorous research, and writing. \n  Policing | Juvenile Delinquency | K-12 | Data Visualization"
  avatarURL = "/images/picture.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  commentsrepo = "jcvincentliu/Personal-Website"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/JunchenVincent"},
    {name = "linkedin", url = "https://www.linkedin.com/in/juncheng-liu-79075315a/"},
    {name = "github", url = "https://github.com/jcvincentliu/"},
  #  {name = "stackoverflow", url = "https://example.com"},
    {name = "email", url = "mailto:liujcv00048@gmail.com"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "About Me"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 4

#  [[menu.main]]
 #   name = "Tags"
 #   pre = "<span data-feather='tag'></span>"
 #   url = "/tags/"
 #   weight = 5
    
    [[menu.main]]
    name = "Resume"
    pre = "<span data-feather='file-text'></span>"
    url = "/files/resume.pdf"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/jcvincentliu/"
    weight = 6
    
  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/juncheng-liu-79075315a/"
    weight = 7



[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
